# Copyright (c) libdragon 2021
# See LICENSE file in the project root for full license information.

name: Build tools using MinGW.
on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        platform: [ 'x64', 'i386' ]


    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64 #TODO: make this a matrix so it also builds for win32?

      - name: Build Tools
        shell: bash
        run: |
          make tools

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libdragon-tools-mingw
          path: |
            ${{ github.workspace }}\**\*.exe