# Copyright (c) libdragon 2021
# See LICENSE file in the project root for full license information.

name: Build tools using MinGW.
on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      platform: [ 'x86', 'x64' ]


    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86 #${{ matrix.platform }}

      - name: Install Dependencies
        shell: bash
        run: |
          # TODO: this dependency is not helpful.
          # Unfortunately using the following does not work!
          # sudo apt-get install libpng-dev libpng++-dev
          # So lets try building and installing the mingw version.
          curl -SL http://downloads.sourceforge.net/project/libpng/01-libpng-master/1.4.1/libpng-1.4.1.tar.gz
          tar -zxvf libpng-1.4.1.tar.gz
          cd libpng-1.4.1
          ./configure –prefix=/mingw
          make
          make install
          cd ..

      - name: Build Tools
        shell: bash
        run: |
          make tools
          # TODO: as well as `png.h` there are also issues with `dumpdfs.c` `malloc` warnings.

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libdragon-tools-mingw #-${{ matrix.platform }}
          path: |
            ${{ github.workspace }}\**\*.exe