# Copyright (c) libdragon 2021
# See LICENSE file in the project root for full license information.

# This workflow will build the tools for Windows using MSYS2 and upload the artifacts.

name: Build Windows tools using MSYS2. 

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { sys: mingw64, arch: x86_64 },
          { sys: mingw32, arch: i686 } # Probably useful for those on Windows XP or below!
        ]
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            sed
            mingw-w64-${{ matrix.arch }}-libpng
            base-devel
            mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - uses: actions/checkout@v2
        with:
          path: ./libdragon
          fetch-depth: 0

      - name: Correct pthread to allow static
        shell: msys2 {0}
        run: |
          sed -z 's/#else\n#define WINPTHREAD_API __declspec(dllimport)/#else\n#define WINPTHREAD_API/' /${{matrix.sys}}/${{ matrix.arch }}-w64-mingw32/include/pthread.h

      - name: Build Tools
        shell: msys2 {0}
        run: |
          cd ./libdragon
          make tools

      - name: "Upload libdragon tool executables"
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}
          path: ./libdragon/tools/*.exe