# Copyright (c) libdragon 2021
# See LICENSE file in the project root for full license information.

# This workflow will build the libdragon N64 GCC toolchain to keep it up-to-date.
name: Build latest libdragon N64 MIPS GCC toolchain

on:
  # This action will take about 40 minutes to run! It is designed to only fire if the build file changes.
  push:
   paths:
     - 'tools/build'
  pull_request:
   paths:
     - 'tools/build'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install linux dependencies
        run: |
          sudo apt-get install libmpfr-dev
          sudo apt-get install texinfo
          sudo apt-get install libmpc-dev

      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Build N64 MIPS GCC toolchain script
        run: |
          mkdir toolchain
          cp tools/build /toolchain
          cd ./toolchain
          ./build

      - name: Upload Docker Container
        run: |
          echo "TODO: Create/Upload the docker container."

      - name: Upload dep package.
        run: |
          echo "TODO: Create upload the debian package."

      - name: Upload Github .deb Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-libdragon-toolchain-debian
          path: |
            ${{ github.workspace }}/**/*.deb