# Copyright (c) libdragon 2021
# See LICENSE file in the project root for full license information.

# This workflow will build the solution and release a nuget.

name: Build libdragon for Windows.

on: [push, pull_request]

defaults:
  run:
    shell: cmd

jobs:
  build-windows-tools:
    name: Build Windows tools.
    timeout-minutes: 15
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install required dependencies
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/tronkko/dirent/master/include/dirent.h --output ./include/dirent.h
          curl -L https://windows.php.net/downloads/php-sdk/deps/vs16/x86/libpng-1.6.34-6-vs16-x86.zip --output libpng.zip

      - name: Extract required dependencies
        shell: pwsh
        run: Expand-Archive -Path 'libpng.zip' -DestinationPath "libpng"

      - name: Build tools using MSVC
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          echo "building chksum64..."
          call cl .\tools\chksum64.c
          echo "building n64tool..."
          call cl .\tools\n64tool.c
          echo "building dumpdfs..."
          call cl .\tools\dumpdfs\dumpdfs.c -I .\include\
          echo "building mkdfs..."
          call cl .\tools\mkdfs\mkdfs.c -I .\include\
          echo "building mksprite..."
          call cl .\tools\mksprite\convtool.c
          call cl /MD .\tools\mksprite\mksprite.c .\libpng\lib\libpng.lib /I .\libpng\include\libpng16\ /link

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libdragon-tools-windows
          path: |
            ${{ github.workspace }}\**\*.exe
