name: Build Windows tools using MYS2. 

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { sys: mingw64, arch: x86_64 },
          { sys: mingw32, arch: i686 }
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            sed
            mingw-w64-${{ matrix.arch }}-libpng
            base-devel
            mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\libdragon" -Recurse

      - name: Correct pthread to allow static
        shell: msys2 {0}
        run: |
          sed -z 's/#else\n#define WINPTHREAD_API __declspec(dllimport)/#else\n#define WINPTHREAD_API/' /mingw64/${{ matrix.arch }}-w64-mingw32/include/pthread.h

      - name: Build Tools
        shell: msys2 {0}
        run: |
          cd /C/libdragon
          make tools

      - name: "Upload executable"
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}
          path: C:/libdragon/tools/*.exe